FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MajesticThai

Choose your favorite Thai-style

## Dishes Collection [/dishes]

### List All Dishes [GET]

+ Response 200 (application/json)

        [
                    {
                        "Name": "Pizza",
                         "url": "/questions/1/choices/1",
                         "Id": 0,
                        "Description":"Flatbread",
                        "Cost":8.50,
                    }, {
                        "Name": "Calzone",
                         "url": "/questions/1/choices/2",
                         "Id": 1,
                        "Description":"Folded pizza",
                        "Cost":9.50,
                    }, {
                        "Name": "Spagetti",
                         "url": "/questions/1/choices/3",
                         "Id": 2,
                        "Description":"Angelhair with red sauce",
                        "Cost":6.50,
                    }, {
                        "Name": "Lasanga",
                         "url": "/questions/1/choices/4",
                         "Id": 3,
                        "Description":"Absolutely no cat hair",
                        "Cost":7.50,
                    }
        ]

## Dish [/dishes/{dish_id}]

+ Parameters
    + dish_id (number) - ID of the Dish

### Show a single dish [GET]

Select the single dish you want and the chef will make it.

+ Response 200 (application/json)

        {
            "Name":Pizza,
            "Id": 0,
            "Description":"Absolutely no cat hair",
            "Cost":8.50,
        }
        
### Make an order [POST]
Recieve an order

+ Request (application/json)

        {
            "Id":213234
            "Time to be ready": "7:45",
            "Customer":"Ted",
            "Total":21.50
            "Dishes":[
                    "Pizza",
                    "Lasanga"
                    ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /orders/1

    + Body

            {
                "Id":213234,
                "Time to be ready": "7:45",
                "Customer":"Ted",
                "Total":21.50,
                "Dishes":[
                        "Pizza",
                        "Lasanga"
                         ]
            }


## Order Collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json)

        [
                    {
                        "Id":213234,
                        "Time to be ready": "7:45",
                        "Customer":"Ted",
                        "Total":21.50,
                        "Dishes":[
                                    "Pizza",
                                    "Lasanga"
                                 ],
                    }, {
                        "Id":645676,
                        "Time to be ready": "5:45",
                        "Customer":"Bill",
                        "Total":11.50,
                        "Dishes":[
                                    "Pizza",
                                 ],
                    }, {
                        "Id":776898,
                        "Time to be ready": "6:45",
                        "Customer":"Suzie",
                        "Total":31.50,
                        "Dishes":[
                                    "Pizza",
                                    "Lasanga",
                                    "Calzone"
                                 ],
                    }, {
                      "Id":123456,
                        "Time to be ready": "4:45",
                        "Customer":"Ted",
                        "Total":10.50,
                        "Dishes":[
                                    "Lasanga"
                                 ]
                    }
        ]

## Order [/Orders/{order_id}]

+ Parameters
    + dish_id (number) - ID of the Dish

### Show a single order [GET]

See a specific order

+ Response 200 (application/json)

        {
                        "Id":123456,
                        "Time to be ready": "4:45",
                        "Customer":"Ted",
                        "Total":10.50,
                        "Dishes":[
                                    "Lasanga"
                                 ]
        }